2024-04-02 01:18:43,182 INFO    MainThread:2276483 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-02 01:18:43,182 INFO    MainThread:2276483 [wandb_setup.py:_flush():76] Configure stats pid to 2276483
2024-04-02 01:18:43,182 INFO    MainThread:2276483 [wandb_setup.py:_flush():76] Loading settings from /net/galaxy/home/koes/vratins/.config/wandb/settings
2024-04-02 01:18:43,182 INFO    MainThread:2276483 [wandb_setup.py:_flush():76] Loading settings from /net/galaxy/home/koes/vratins/graphpocket/gnn/wandb/settings
2024-04-02 01:18:43,182 INFO    MainThread:2276483 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-02 01:18:43,183 INFO    MainThread:2276483 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-02 01:18:43,183 INFO    MainThread:2276483 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'gnn/train.py', 'program_abspath': '/net/galaxy/home/koes/vratins/graphpocket/gnn/train.py', 'program': '/net/galaxy/home/koes/vratins/graphpocket/gnn/train.py'}
2024-04-02 01:18:43,183 INFO    MainThread:2276483 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-02 01:18:43,183 INFO    MainThread:2276483 [wandb_init.py:_log_setup():527] Logging user logs to /net/galaxy/home/koes/vratins/graphpocket/gnn/wandb/run-20240402_011843-f9oynx1z/logs/debug.log
2024-04-02 01:18:43,183 INFO    MainThread:2276483 [wandb_init.py:_log_setup():528] Logging internal logs to /net/galaxy/home/koes/vratins/graphpocket/gnn/wandb/run-20240402_011843-f9oynx1z/logs/debug-internal.log
2024-04-02 01:18:43,183 INFO    MainThread:2276483 [wandb_init.py:init():567] calling init triggers
2024-04-02 01:18:43,183 INFO    MainThread:2276483 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {'directories': {'pockets': '~/dataset_graph/data', 'pos_list': '~/dataset_graph/TOUGH-M1/TOUGH-M1_positive.list', 'neg_list': '~/dataset_graph/TOUGH-M1/TOUGH-M1_negative.list', 'cluster_map': '../cluster_map.pkl', 'result_dir': '../results'}, 'model': {'input_scalar_size': 4, 'output_scalar_size': 128, 'vector_size': 16, 'n_convs': 3, 'dropout': 0.2, 'vector_gating': True, 'xavier_init': True}, 'loss': {'margin': 1.0}, 'train': {'n_epochs': 20, 'batch_size': 64, 'n_workers': 4, 'optimizer': {'type': 'Adam', 'lr': 0.001, 'weight_decay': 0.01}, 'scheduler': {'type': 'ReduceLROnPlateau', 'params': {'mode': 'min', 'factor': 0.1, 'patience': 10, 'verbose': True}}, 'gradient_clipping': True, 'grad_clip_val': 1.0}, 'wandb': None}
2024-04-02 01:18:43,183 INFO    MainThread:2276483 [wandb_init.py:init():617] starting backend
2024-04-02 01:18:43,184 INFO    MainThread:2276483 [wandb_init.py:init():621] setting up manager
2024-04-02 01:18:43,186 INFO    MainThread:2276483 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-02 01:18:43,194 INFO    MainThread:2276483 [wandb_init.py:init():629] backend started and connected
2024-04-02 01:18:43,200 INFO    MainThread:2276483 [wandb_init.py:init():721] updated telemetry
2024-04-02 01:18:43,220 INFO    MainThread:2276483 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-04-02 01:18:43,500 INFO    MainThread:2276483 [wandb_run.py:_on_init():2344] communicating current version
2024-04-02 01:18:43,579 INFO    MainThread:2276483 [wandb_run.py:_on_init():2353] got version response 
2024-04-02 01:18:43,579 INFO    MainThread:2276483 [wandb_init.py:init():805] starting run threads in backend
2024-04-02 01:18:50,678 INFO    MainThread:2276483 [wandb_run.py:_console_start():2323] atexit reg
2024-04-02 01:18:50,679 INFO    MainThread:2276483 [wandb_run.py:_redirect():2178] redirect: wrap_raw
2024-04-02 01:18:50,685 INFO    MainThread:2276483 [wandb_run.py:_redirect():2243] Wrapping output streams.
2024-04-02 01:18:50,685 INFO    MainThread:2276483 [wandb_run.py:_redirect():2268] Redirects installed.
2024-04-02 01:18:50,687 INFO    MainThread:2276483 [wandb_init.py:init():848] run started, returning control to user process
2024-04-02 01:18:55,330 WARNING MsgRouterThr:2276483 [router.py:message_loop():77] message_loop has been closed
